# Generated by Django 2.2.9 on 2020-02-27 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('lines', models.CharField(max_length=400)),
                ('age_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)])),
                ('image', models.CharField(max_length=200)),
            ],
        ),
    ]
