# Generated by Django 2.2.9 on 2020-02-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0002_auto_20200227_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='line1',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
