# Generated by Django 2.2.9 on 2020-02-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0003_story_line1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='line1',
            new_name='line2',
        ),
    ]
