# Generated by Django 2.2.9 on 2020-02-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0004_auto_20200227_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='line2',
        ),
        migrations.AddField(
            model_name='story',
            name='lineStart',
            field=models.CharField(default='SOME STRING', max_length=400),
        ),
    ]
