# Generated by Django 2.2.9 on 2020-02-27 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storys', '0005_auto_20200227_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='lineStart',
            field=models.CharField(default='Your first line', max_length=400),
        ),
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='storys', to='storys.Genre'),
        ),
    ]
