# Generated by Django 2.2.9 on 2020-02-27 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0006_auto_20200227_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='story',
        ),
        migrations.AddField(
            model_name='story',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storys', to='storys.Line'),
        ),
    ]
