# Generated by Django 2.2.9 on 2020-02-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0008_auto_20200227_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='type',
            new_name='text',
        ),
    ]
