# Generated by Django 2.2.9 on 2020-02-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0009_auto_20200227_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='storys', to='genres.Genre'),
        ),
    ]
