# Generated by Django 2.2.9 on 2020-03-01 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0010_auto_20200228_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storys', to=settings.AUTH_USER_MODEL),
        ),
    ]
