# Generated by Django 2.2.9 on 2020-03-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storys', '0011_auto_20200301_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='genre',
        ),
        migrations.AddField(
            model_name='story',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
